dist: focal
language: php
php:
    - 8.1.2
before_script:
    - composer install --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs
script:
    - mkdir -p build/test
    - apps/MusicLabel/api/bin/console app:dump-env test --env test
    - apps/MusicLabel/api/bin/console doctrine:database:drop --force --quiet
    - apps/MusicLabel/api/bin/console doctrine:database:create --no-interaction --quiet
    - apps/MusicLabel/api/bin/console doctrine:schema:update --force --no-interaction --quiet
    - XDEBUG_MODE=coverage vendor/bin/phpunit -c phpunit.xml.dist
after_success:
    - travis_retry php vendor/bin/php-coveralls
    - travis_retry php vendor/bin/php-coveralls -v