version: "3.8"

#
# base docker-compose file
#

services:

    php:
        image: masfernandez/${COMPOSE_PROJECT_NAME}-php-${ENV}:${VERSION}
        build:
            context: ./docker/php
            target: ${ENV}
            args:
                PHP_VERSION: ${PHP_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-php
        volumes:
            - .:/var/www/html
            - ./docker/php/etc/supervisor/conf.d:/etc/supervisor.d
        environment:
            DATABASE_URL_MYSQL: mysql://${MYSQL_USER:-db_user}:${MYSQL_PASSWORD:-db_pass}@${SYMFONY_MYSQL_DB_HOST:-mysql80}/${MYSQL_DATABASE:-music_label_backend}?serverVersion=8.0&charset=utf8
            DATABASE_URL_MARIADB: mysql://${MARIADB_USER:-db_user}:${MARIADB_PASSWORD:-db_pass}@${SYMFONY_MARIADB_DB_HOST:-mariadb106}/${MARIADB_DATABASE:-music_label_backend}?serverVersion=mariadb-10.6.4&charset=utf8
            ASYNC_TRANSPORT_DSN: amqp://${RABBITMQ_DEFAULT_USER:-rabbit_user}:${RABBITMQ_DEFAULT_PASS:-rabbit_pass}@${SYMFONY_RABBITMQ_HOST:-rabbitmq}/%2f/messages

networks:
    musiclabel:
    db:
    redis:
    elk: