version: "3.8"

#
# local-dev env docker-compose file
#
# This file override some prod file values, to use when development (xdebug, disable opcache.preload, etc.)

services:

    php:
        environment:
            # Configure server name below, and enable xdebug with make enable-xdebug
            PHP_IDE_CONFIG: serverName=docker
        volumes:
            - ./docker/php/usr/local/etc/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
            #- ./var/log/xdebug/xdebug.log:/tmp/xdebug.log