parameters:

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Private services by default


    # Redis
    Redis: '@snc_redis.default'
    Masfernandez\MusicLabel\Infrastructure\Api\Repository\Cache\Redis\Client:
        public : true
        autowire: true
        arguments: ['@snc_redis.default']


    # Aliases dev
    Masfernandez\Tests\MusicLabel\Shared\Domain\Persistence\RepositoryCleaner:
        class: Masfernandez\Tests\MusicLabel\Shared\Infrastructure\Persistence\MySql\MySqlCleaner


    # Aliases common
    Masfernandez\MusicLabel\Infrastructure\Api\Bus\Event\EventPublisher:
        class: Masfernandez\MusicLabel\Infrastructure\Api\Bus\Event\RabbitMq\RabbitMqEventPublisher

    # Auth
    Masfernandez\MusicLabel\Auth\Domain\User\TokenRepository:
        class: Masfernandez\MusicLabel\Infrastructure\Api\Repository\Auth\DoctrineTokenRepository

    Masfernandez\MusicLabel\Auth\Domain\User\UserRepository:
        class: Masfernandez\MusicLabel\Infrastructure\Api\Repository\Auth\DoctrineUserRepository

    # Catalog
    Masfernandez\MusicLabel\Backoffice\Catalog\Domain\Album\AlbumRepository:
        class: Masfernandez\MusicLabel\Infrastructure\Api\Repository\Catalog\DoctrineAlbumRepository

    Masfernandez\MusicLabel\Backoffice\Catalog\Domain\Artist\ArtistRepository:
        class: Masfernandez\MusicLabel\Infrastructure\Api\Repository\Catalog\DoctrineArtistRepository

    Masfernandez\MusicLabel\Backoffice\Catalog\Domain\Label\LabelRepository:
        class: Masfernandez\MusicLabel\Infrastructure\Api\Repository\Catalog\DoctrineLabelRepository

    Masfernandez\MusicLabel\Backoffice\Catalog\Domain\Track\TrackRepository:
        class: Masfernandez\MusicLabel\Infrastructure\Api\Repository\Catalog\DoctrineTrackRepository

    Masfernandez\MusicLabel\Backoffice\Catalog\Domain\Album\CacheInMemory:
        class: Masfernandez\MusicLabel\Infrastructure\Api\Repository\Cache\Redis\Client
