server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://${LOKI_HOST:-loki}:${LOKI_PORT:-3100}/loki/api/v1/push

scrape_configs:
    - job_name: musiclabel-symfony
      static_configs:
          - targets:
                - localhost
            labels:
                job: musiclabel-symfony
                __path__: /var/log/symfony/*log
    - job_name: musiclabel-nginx
      static_configs:
          - targets:
                - localhost
            labels:
                job: musiclabel-nginx
                __path__: /var/log/nginx/*log