version: '3.9'

services:

    promtail:
        image: grafana/promtail:2.5.0
        volumes:
            - /var/log:/var/log
            - ./config.yaml:/etc/promtail/config.yml
        command: -config.file=/etc/promtail/config.yml
        environment:
            # For Nginx-proxy
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_PORT=${VIRTUAL_PORT}
        restart: ${RESTART}
        networks:
            - proxy
            - grafana

networks:
    grafana:
        external: true
    proxy:
        external: true
